### ISSUE TITLE
Does not recognize many local names, causes app to crash

### ISSUE THREAD

**Issue by NashBaughn** [TiagoDanin/Locale-Codes#25]
Great package but not all the methods are entriely useable. 

Using `locale.where("local", inputValue)` results in `TypeError: Cannot read properties of null (reading 'toLowerCase')` for many cases. 

At first I thought it was due to different charcter sets, but no. Using local names "Brezhoneg", "Español", "العربية",  "English"
and more all result in errors. 

Oddly enough the local name "Afaraf" returns correctly (I imagine there are more, but did not find any).

**Comment by ndtreviv** [comment]
Another example:

```
> locale.where('location', 'us').name;
Uncaught TypeError: Cannot read properties of null (reading 'toLowerCase')
    at /Users/me/example/node_modules/locale-codes/index.js:51:42
    at Array.find (<anonymous>)
    at Object.where (/Users/me/example/node_modules/locale-codes/index.js:51:13)
 ```

**Comment by TiagoDanin** [comment]
Fixed in [v2.0.0](https://github.com/TiagoDanin/Locale-Codes/releases/tag/v2.0.0) (`locale-codes@2.0.0` on npm).

The crash came from `element[key].toLowerCase()` running against entries whose `local` or `location` is `null` — 437 of the 862 locales have no localised name. Comparison now goes through a helper that treats a null field as "no match" instead of dereferencing it:

```js
locale.where('local', 'Español')    // { name: 'Spanish', tag: 'es', ... }
locale.where('local', 'Brezhoneg')  // { name: 'Breton', tag: 'br', ... }
locale.where('location', 'us')      // undefined - no throw
```

Regression tests cover all the values reported here. Thanks @ndtreviv for the extra repro.
