### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'toLowerCase')

### ISSUE THREAD

**Issue by missinglink** [TiagoDanin/Locale-Codes#41]
```
node
Welcome to Node.js v21.7.3.
Type ".help" for more information.

> const locale = require('locale-codes')
undefined

> locale.where('iso639-1', 'en')
Uncaught TypeError: Cannot read properties of null (reading 'toLowerCase')
    at /Users/peter/code/missinglink/places/node_modules/locale-codes/index.js:51:42
    at Array.find (<anonymous>)
    at Object.where (/Users/peter/code/missinglink/places/node_modules/locale-codes/index.js:51:13)
```

**Comment by Shatlyk1011** [comment]
I changed locally the line you changed, but the error still remains.
